language: generic
before_deploy:
- pip install -r src/requirements.txt -t lambda-env
- cp -r src/project.py lambda-env/
- mkdir lambda-env/data
- cp data/stats.data page
- cd lambda-env/
- zip -r ../page/projectSrc.zip *
- cd ..
deploy:
- provider: s3
  access_key_id: $baseball_project_access_key_id
  secret_access_key: $baseball_project_secret_key
  bucket: lilly-carruth-smith-craig-baseball-project-dev
  local-dir: page
  region: us-east-1
  skip-cleanup: true
  on:
    branch: dev
    repo: cs450LillyCarruthSmithCraigTeam/cs450project
- provider: s3
  access_key_id: $baseball_project_access_key_id
  secret_access_key: $baseball_project_secret_key
  bucket: lilly-carruth-smith-craig-baseball-project
  local-dir: page
  region: us-east-1
  skip-cleanup: true
  on:
    branch: master
    repo: cs450LillyCarruthSmithCraigTeam/cs450project
